Double click changes the account
DefineX-Studios/parsec-account-switcher pull request #66
Opened 2023-12-18 11:53 UTC by mohsinshabir1234

Have added a  double click feature on accounts to change the accout.

2023-12-18 20:57 UTC, adsau59 requested changes

2023-12-18 20:57 UTC, adsau59 commented on gui/control.js
> +        });
use arrow function for clear code

2023-12-18 20:57 UTC, adsau59 commented on gui/control.js
>  function render() {
correct indentation and add new line between functions for cleaner code

2023-12-18 20:57 UTC, adsau59 commented on gui/style.css
> +  /* Add your custom focus styles here, for example: */
is this comment relevent to our code base?

2023-12-20 13:32 UTC, mohsinshabir1234 reviewed
I have done the requested changes. Kindly check.

2023-12-20 13:33 UTC, mohsinshabir1234 commented
#66

2023-12-20 15:08 UTC, adsau59 requested changes

2023-12-20 15:08 UTC, adsau59 commented on gui/control.js
> +
create different pull request for loading issue

2023-12-20 15:08 UTC, adsau59 commented on gui/control.js
> +}
please make sure changes doesn't include things u haven't changed

2023-12-20 15:08 UTC, adsau59 commented on gui/control.js
> +    showLoadingOverlay(); // Show loading overlay before the initialization process
why are we doing this in main?

2023-12-27 08:09 UTC, adsau59 commented
duplicate of #68 closing

2023-12-27 08:09 UTC, closed without merging